### ISSUE TITLE
AttributeError: module 'odoo' has no attribute 'tools'

### ISSUE THREAD

**Issue by M-Saeb** [camptocamp/pytest-odoo#51]
### What I'm doing:
I have an odoo 15 instance that I run from the source code using `.venv` virtual environment
After activating the enviroment using `source /odoo15/.venv/activate`
I ran the command `pyhton -m pip install pytest-odoo` than I ran
```
python -m pytest -s --odoo-database=15-demo-2 --odoo-log-level=debug_sql
```

### What I expected:
to see tests output

### What I got:
the following error code:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/odoo15/.venv/lib/python3.8/site-packages/pytest/__main__.py", line 5, in <module>
    raise SystemExit(pytest.console_main())
  File "/odoo15/.venv/lib/python3.8/site-packages/_pytest/config/__init__.py", line 187, in console_main
    code = main()
  File "/odoo15/.venv/lib/python3.8/site-packages/_pytest/config/__init__.py", line 164, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File "/odoo15/.venv/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/odoo15/.venv/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/odoo15/.venv/lib/python3.8/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/odoo15/.venv/lib/python3.8/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/odoo15/.venv/lib/python3.8/site-packages/pluggy/_callers.py", line 34, in _multicall
    next(gen)  # first yield
  File "/odoo15/.venv/lib/python3.8/site-packages/pytest_odoo.py", line 58, in pytest_cmdline_main
    odoo.tools.config.parse_config(options)
AttributeError: module 'odoo' has no attribute 'tools'
```

**Comment by yvaucher** [comment]
What you have in `odoo` doesn't seems to be the official odoo.

https://github.com/odoo/odoo/tree/17.0/odoo/tools
